spring.application.name=auradocs

spring.mongodb.uri=mongodb://localhost:27017/auradocs

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.chat.options.temperature=0.7

server.port=8080

logging.level.org.springframework.ai=DEBUG
